version: "3.7"
services:
  app-server:
    image: sagheergmit/final-year-project:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: "mongodb://db"
    networks:
      - fyp
  app-client:
    image: sagheergmit/frontendfyp:latest
    ports:
      - 80:3000
    restart: always
    depends_on:
      - app-server
    networks:
      - fyp
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fypdb
    volumes:
      - db-data:/data/db
    networks:
      - fyp
volumes:
  db-data:
networks:
  fyp:
