version: "3.7"
services:
  app-server:
    image: final-year-project:latest
    ports:
      - 8085:8080
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: "mongodb://db"
    networks:
      - backend
      - frontend

  app-client:
    image: frontendfyp:latest
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fypdb
    volumes:
      - db-data:/data/db 
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
